import type { TerrestrialModelResult } from "../model/types.js";
import { formatUsdCompact } from "../../app/lib/formatters.js";
import styles from "./TerrestrialPanel.module.css";

interface Props {
  result: TerrestrialModelResult;
}

/** Self-wrapping lifecycle cost breakdown, mirroring CostBreakdown.tsx's pattern on the ocean side. */
export function TerrestrialResults({ result }: Props) {
  const buckets = [
    {
      label: "Power system",
      description: "CCGT capital, fuel, fixed and variable O&M, decommissioning",
      value: result.costs.buckets_undiscounted.power_system_usd,
      color: "var(--cat-power)",
    },
    {
      label: "Data-center facility",
      description: "Electrical, mechanical/cooling, civil/shell, maintenance",
      value: result.costs.buckets_undiscounted.data_center_facility_usd,
      color: "var(--cat-facility)",
    },
    {
      label: "Compute hardware and replacement",
      description: "Installed compute capex plus expected failure replacement",
      value: result.costs.buckets_undiscounted.compute_and_replacement_usd,
      color: "var(--cat-compute)",
    },
    {
      label: "Workload data transfer",
      description: "External network traffic generated by delivered compute",
      value: result.costs.buckets_undiscounted.workload_data_transfer_usd,
      color: "var(--cat-workload)",
    },
  ];
  const bucketTotal = buckets.reduce((sum, b) => sum + b.value, 0);

  return (
    <div className="card">
      <div className={styles.breakdownWrap}>
        <div className={styles.breakdownTitleRow}>
          <span className={styles.breakdownTitle}>Lifecycle cost breakdown</span>
          <span className={`${styles.breakdownTotal} num`}>{formatUsdCompact(bucketTotal)} total</span>
        </div>

        <div className={styles.bar}>
          {buckets.map((b) => (
            <div
              key={b.label}
              className={styles.segment}
              style={{ flexBasis: `${(b.value / bucketTotal) * 100}%`, background: b.color }}
              title={`${b.label}: ${formatUsdCompact(b.value)}`}
            />
          ))}
        </div>

        <div className={styles.legend}>
          {buckets.map((b) => (
            <div key={b.label} className={styles.legendItem}>
              <span className={styles.swatch} style={{ background: b.color }} />
              <span className={styles.legendText}>
                <span className={styles.legendLabel}>{b.label}</span>
                <span className={`${styles.legendValue} num`}>
                  {formatUsdCompact(b.value)}{" "}
                  <span className={styles.legendPercent}>({((b.value / bucketTotal) * 100).toFixed(1)}%)</span>
                </span>
                <span className={styles.legendDescription}>{b.description}</span>
              </span>
            </div>
          ))}
        </div>

        <p className={styles.boundary}>{result.methodology.lifecycle_cost_boundary}</p>
      </div>
    </div>
  );
}
