import type { TerrestrialModelResult } from "../model/types.js";
import { TERRESTRIAL_POWER_SOURCE_SPECS } from "../model/defaults.js";
import { CostBreakdownList, type CostCategory } from "../../app/components/CostBreakdownList.js";

interface Props {
  result: TerrestrialModelResult;
}

/** Terrestrial lifecycle cost breakdown; shares the ranked bar list with the ocean side so the pair reads identically. */
export function TerrestrialResults({ result }: Props) {
  const spec = TERRESTRIAL_POWER_SOURCE_SPECS[result.inputs.power_source];
  const isCcgt = result.inputs.power_source === "ccgt";
  const powerSystemDescription = isCcgt
    ? "CCGT capital, fuel, fixed and variable O&M, decommissioning"
    : `${spec.label} capital${spec.hasStorage ? " (incl. battery)" : ""}, fixed O&M${spec.hasStorage ? ", storage O&M" : spec.hasVariableOm ? ", variable O&M" : ""}, decommissioning`;

  const categories: CostCategory[] = [
    {
      label: "Power system",
      description: powerSystemDescription,
      value: result.costs.buckets_undiscounted.power_system_usd,
      color: "var(--cat-power)",
    },
    {
      label: "Data-center facility",
      description: "Electrical, mechanical/cooling, civil/shell, maintenance",
      value: result.costs.buckets_undiscounted.data_center_facility_usd,
      color: "var(--cat-facility)",
    },
    {
      label: "Compute hardware and replacement",
      description: "Installed compute capex plus expected failure replacement",
      value: result.costs.buckets_undiscounted.compute_and_replacement_usd,
      color: "var(--cat-compute)",
    },
    {
      label: "Fiber",
      description: "External network traffic generated by delivered compute",
      value: result.costs.buckets_undiscounted.workload_data_transfer_usd,
      color: "var(--cat-workload)",
    },
  ];

  return (
    <CostBreakdownList
      title="Lifecycle cost breakdown"
      categories={categories}
      footnote={result.methodology.lifecycle_cost_boundary}
    />
  );
}
