import type { ModelResult } from "../../model/index.js";
import { formatUsdCompact } from "../lib/formatters.js";
import styles from "./CostBreakdown.module.css";

interface Props {
  result: ModelResult;
}

export function CostBreakdown({ result }: Props) {
  const { costs } = result;

  const categories = [
    {
      label: "Physical node cost",
      description: "Hull, PTO, battery, and onboard systems capex",
      value: costs.buckets.initial_non_compute_physical_usd,
      color: "var(--cat-physical)",
    },
    {
      label: "Compute hardware and maintenance",
      description: "Compute capex plus block and total-payload replacement",
      value: costs.buckets.compute_and_replacement_usd,
      color: "var(--cat-compute)",
    },
    {
      label: "Planned deployment and non-compute maintenance",
      description: "Scheduled tug trips, five-year maintenance, retirement",
      value:
        costs.lineItems.normal_tug_cost_usd +
        costs.lineItems.scheduled_node_maintenance_cost_usd +
        costs.lineItems.node_retirement_cost_usd_total,
      color: "var(--cat-planned)",
    },
    {
      label: "Failures and recovery",
      description: "Unexpected tug/retrieval, repairs, catastrophic cleanup, total-loss replacement",
      value:
        costs.lineItems.unexpected_tug_cost_usd +
        costs.lineItems.mode_4_5_non_compute_replacement_cost_usd +
        costs.lineItems.unexpected_mechanical_repair_cost_usd +
        costs.lineItems.mode_5_catastrophic_cost_usd_total,
      color: "var(--cat-failure)",
    },
    {
      label: "Workload data transfer",
      description: "External network traffic generated by delivered compute",
      value: costs.buckets.workload_data_transfer_usd,
      color: "var(--cat-workload)",
    },
  ];

  const total = categories.reduce((sum, c) => sum + c.value, 0);

  return (
    <div className="card">
      <div className={styles.wrap}>
        <div className={styles.titleRow}>
          <span className={styles.title}>Lifecycle cost breakdown</span>
          <span className={`${styles.totalValue} num`}>{formatUsdCompact(total)} total</span>
        </div>

        <div className={styles.bar}>
          {categories.map((c) => (
            <div
              key={c.label}
              className={styles.segment}
              style={{ flexBasis: `${(c.value / total) * 100}%`, background: c.color }}
              title={`${c.label}: ${formatUsdCompact(c.value)}`}
            />
          ))}
        </div>

        <div className={styles.legend}>
          {categories.map((c) => (
            <div key={c.label} className={styles.legendItem}>
              <span className={styles.swatch} style={{ background: c.color }} />
              <span className={styles.legendText}>
                <span className={styles.legendLabel}>{c.label}</span>
                <span className={`${styles.legendValue} num`}>
                  {formatUsdCompact(c.value)}{" "}
                  <span className={styles.legendPercent}>({((c.value / total) * 100).toFixed(1)}%)</span>
                </span>
              </span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
