import type { ModelResult } from "../../model/index.js";
import { CostBreakdownList, type CostCategory } from "./CostBreakdownList.js";

interface Props {
  result: ModelResult;
}

export function CostBreakdown({ result }: Props) {
  const { costs } = result;

  const categories: CostCategory[] = [
    {
      label: "Physical node cost",
      description: "Hull, PTO, battery, and onboard systems capex",
      value: costs.buckets.initial_non_compute_physical_usd,
      color: "var(--cat-physical)",
    },
    {
      label: "Compute hardware and maintenance",
      description: "Compute capex plus block and total-payload replacement",
      value: costs.buckets.compute_and_replacement_usd,
      color: "var(--cat-compute)",
    },
    {
      label: "Planned deployment and non-compute maintenance",
      description: "Scheduled tug trips, five-year maintenance, retirement",
      value:
        costs.lineItems.normal_tug_cost_usd +
        costs.lineItems.scheduled_node_maintenance_cost_usd +
        costs.lineItems.node_retirement_cost_usd_total,
      color: "var(--cat-planned)",
    },
    {
      label: "Failures and recovery",
      description: "Unexpected tug/retrieval, repairs, catastrophic cleanup, total-loss replacement",
      value:
        costs.lineItems.unexpected_tug_cost_usd +
        costs.lineItems.mode_4_5_non_compute_replacement_cost_usd +
        costs.lineItems.unexpected_mechanical_repair_cost_usd +
        costs.lineItems.mode_5_catastrophic_cost_usd_total,
      color: "var(--cat-failure)",
    },
    {
      label: "Workload data transfer",
      description: "External network traffic generated by delivered compute",
      value: costs.buckets.workload_data_transfer_usd,
      color: "var(--cat-workload)",
    },
  ];

  return <CostBreakdownList title="Lifecycle cost breakdown" categories={categories} />;
}
